version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name:
      app_nginx
    ports:
      - 7500:80
    volumes:
      - ../app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    container_name:
      app_php
    volumes:
      - ../app:/usr/share/nginx/html